import { DoctorInfo } from '../models/doctor-info';

export const REPORT_DOCTORS: DoctorInfo[] = [
  {
    id: '1',
    nome: 'Giovanni Mario',
    cognome: 'Rapisarda',
    specialita: 'Medicina Interna',
    tipo: 'medico',
  },
  {
    id: '2',
    nome: 'Rosario',
    cognome: 'Scuderi',
    specialita: 'Medicina Interna',
    tipo: 'medico',
  },
  {
    id: '3',
    nome: 'Andrea',
    cognome: 'Crafa',
    specialita: 'Endocrinologia',
    tipo: 'medico',
  },
  {
    id: '4',
    nome: 'Agata',
    cognome: 'Di Dio',
    specialita: 'Urologia',
    tipo: 'medico',
  },
  {
    id: '5',
    nome: 'Antonio',
    cognome: 'Di Salvo',
    specialita: 'Dermatologia',
    tipo: 'medico',
  },
  {
    id: '6',
    nome: 'Livia',
    cognome: 'Liguori',
    specialita: 'Dermatologia',
    tipo: 'medico',
  },
  {
    id: '7',
    nome: 'Bruna',
    cognome: "D'Amico",
    specialita: 'Medicina Estetica',
    tipo: 'medico',
  },
  {
    id: '8',
    nome: 'Simona Raffaela',
    cognome: 'Zappala',
    specialita: 'Medicina Estetica',
    tipo: 'medico',
  },
  {
    id: '9',
    nome: 'Simona Raffaela',
    cognome: 'Zappala',
    specialita: 'Dietologia',
    tipo: 'medico',
  },
  {
    id: '10',
    nome: 'Rosario Emanuele Carlo',
    cognome: 'Distefano',
    specialita: 'Ginecologia',
    tipo: 'medico',
  },
  {
    id: '11',
    nome: 'Saveria Maria',
    cognome: 'Cantone',
    specialita: 'Ginecologia',
    tipo: 'medico',
  },
  {
    id: '12',
    nome: 'Giovanni',
    cognome: "D'Agosta",
    specialita: 'Chirurgia Plastica',
    tipo: 'medico',
  },
  {
    id: '13',
    nome: 'Giuseppe',
    cognome: 'Bottaro',
    specialita: 'Cardiologia',
    tipo: 'medico',
  },
  {
    id: '14',
    nome: 'Matteo',
    cognome: 'Cavallo',
    specialita: 'Chirurgia Vascolare',
    tipo: 'medico',
  },
  {
    id: '15',
    nome: 'Vincenzo',
    cognome: 'Maccarrone',
    specialita: 'Reumatologia',
    tipo: 'medico',
  },
  {
    id: '16',
    nome: 'Pietro',
    cognome: 'Palamidessi',
    specialita: 'Pneumologia',
    tipo: 'medico',
  },
  {
    id: '17',
    nome: 'Pietro',
    cognome: 'Palamidessi',
    specialita: 'Medicina Generale',
    tipo: 'medico',
  },
  {
    id: '18',
    nome: 'Barbara',
    cognome: 'Martino',
    specialita: 'Senologia',
    tipo: 'medico',
  },
  {
    id: '19',
    nome: 'Sebastiano',
    cognome: 'Arena',
    specialita: 'Neurologia',
    tipo: 'medico',
  },
  {
    id: '20',
    nome: 'Giacomo',
    cognome: 'Di Mulo',
    specialita: 'Biologia nutrizionale',
    tipo: 'medico',
  },
  {
    id: '21',
    nome: 'Ilenia',
    cognome: 'Russo',
    specialita: 'Ostetricia',
    tipo: 'medico',
  },
  {
    id: '22',
    nome: 'Ilenia',
    cognome: 'Russo',
    specialita: 'Dietistica',
    tipo: 'medico',
  },
  {
    id: '23',
    nome: 'Claudia',
    cognome: 'Maugeri',
    specialita: 'Chirurgia maxillo-facciale',
    tipo: 'medico',
  },
  {
    id: '24',
    nome: 'Morena',
    cognome: 'Porto',
    specialita: 'Allergologia',
    tipo: 'medico',
  },
  {
    id: '25',
    nome: 'Giorgia',
    cognome: 'Patane',
    specialita: 'Tecnico di Neurofisiopatologia',
    ruolo: 'TNFP',
    tipo: 'tnfp',
    displayName: 'Dott.ssa Giorgia Patane',
  },
];
